import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page d-flex">
        <div className="flex-grow-1 mt-5">
          <h1 className="text-primary text-center">Sample Project Setup</h1>
        </div>
      </main>
    </>
  );
}
